[package]
name = "rgb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"

[dependencies.hidapi]
version = "*"
default-features = false
features=["linux-static-hidraw"]
